### create team
POST http://localhost:3000/team/create HTTP/1.1
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

{
    "name" : "code masters",
    "description" : "text for test for create new team",
    "username" : "codemasters.8"
}

### get all teams
GET http://localhost:3000/team/list HTTP/1.1
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

### get team by id
GET http://localhost:3000/team/62b1ca6879c5d687214eeef4 HTTP/1.1
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

### get my teams
GET http://localhost:3000/team/me HTTP/1.1
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

### remove team by id
DELETE http://localhost:3000/team/remove/62b1ca8f79c5d687214eeefc HTTP/1.1
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

### invite user to team
GET http://localhost:3000/team/invite/62b2db1273e5e1b76d985e48/alimehrpoya HTTP/1.1
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json